### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by aycanurun** [abhinavk99/crypto-bot#8]
Hi,
Can you explaine steps No.5 and N0.6?

Where is repo folder? You mean dotenv folder under lib folder?

Creating .env file with which name and to where?

**Comment by abhinavk99** [comment]
By repo folder i meant the root folder of the project. There's no dotenv folder or lib folder. 

The .env file should be named .env and put in the root folder of the project.

**Comment by aycanurun** [comment]
Thanks for explanation but its not letting make file .env (without a file name)
I made bot.env and then tried to rename file (delete file name) but can not save the file after deleting its name

**Comment by abhinavk99** [comment]
If you're using windows, try following this 

https://stackoverflow.com/questions/5004633/how-do-i-manually-create-a-file-with-a-dot-prefix-in-windows-for-example

**Comment by aycanurun** [comment]
Worked now. Thanks alot
